version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rake db:create db:schema:load
      - run: bundle exec rspec